id: A3789E697
title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as Ornaments
  of the Practice Lineage'
type: translation
pechas:
- I47FF7246
- I08408788
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:34.168115
  last_modified_at: 2023-01-04 13:01:34.168124
  collections:
  - Marpa Lotsāwa Series
  - Works of Tibetan Masters
alignment_to_base:
  I47FF7246/9057: E210
  I08408788/776E: E210
